#!/usr/bin/env bash
# prints 'Best School' on 10 linesusing the while loop

i=1
while (( "$i" <= 10 )); do
	if (( "$i" == 4 )); then
		echo "bad luck"
	elif [ "$i" -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
