#!/usr/bin/env bash
# Performs git adding, commiting and pushing

if [ -e "$1" ]
	then
		git add "$1"
		if [ -n "$2" ]
			then git commit -m "$2" && git push
			else echo "No commit message"
		fi
	else
		echo "'$1' doesn't exist"
fi
